### ISSUE TITLE
Errors with floats

### ISSUE THREAD

**Issue by Cowski0** [vinrato/phonoid#1]
Hi, I'm on python 3.10.4, and received errors after first running the program, there were type errors on lines 34 and 56, 
quick fix. just changed line 34:
    rect = QRect((image.width() - imgsize) / 2, (image.height() - imgsize) / 2, imgsize, imgsize,)
to 
    rect = QRect(int((image.width() - imgsize) / 2),int((image.height() - imgsize) / 2),imgsize,imgsize,)

and did the same on line 56, changing it to 
    pm = pm.scaled(int(size), int(size), Qt.KeepAspectRatio,Qt.SmoothTransformation)

Simple fix, may be only me, thought I should mention it anyway. Look forward to seeing what will happen with this project, good luck!

**Comment by blitpxl** [comment]
PyQt5 doesn't work that well on python 3.10. this project was originally developed with python 3.8.10. This error is usually avoided in python 3.8 because it will implicitly convert the integers to floats. Somehow PyQt5 failed to do so in python 3.10

**Comment by blitpxl** [comment]
> PyQt5 doesn't work that well on python 3.10. this project was originally developed with python 3.8.10. This error is usually avoided in python 3.8 because it will implicitly convert the integers to floats. Somehow PyQt5 failed to do so in python 3.10

I meant floats to integers
